/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment12client;

import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.http.HttpResponse;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpDelete;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClients;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Jesmaias David
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        createBtn = new javax.swing.JButton();
        readBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuCB = new javax.swing.JComboBox<>();
        rightPanel = new javax.swing.JPanel();
        createBookPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titleBookCreatetf = new javax.swing.JTextField();
        categoryBookCreatetf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        authorBookCreatetf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addBookCreateBtn = new javax.swing.JButton();
        createCustomerPanel = new javax.swing.JPanel();
        fnCustomerCreateTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lnCustomerCreatetf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pnCiustomerCreatetf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addCustomerBtn = new javax.swing.JButton();
        createAuthorPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fnAuthorCreatetf = new javax.swing.JTextField();
        lnAuthorCreatetf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        eAuthorCreatetf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        authorCreateBtn = new javax.swing.JButton();
        readBookPanel = new javax.swing.JPanel();
        readBookIdtf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        readBookBtn = new javax.swing.JButton();
        readAllBookBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        readBookta = new javax.swing.JTextArea();
        readCustomerPanel = new javax.swing.JPanel();
        readCustomerIdtf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        readCustomerBtn = new javax.swing.JButton();
        readAllCustomerBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        readCustomerta = new javax.swing.JTextArea();
        readAuthorPanel = new javax.swing.JPanel();
        readAuthorIdtf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        readAuthorBtn = new javax.swing.JButton();
        readAllAuthorBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        readAuthorta = new javax.swing.JTextArea();
        UpdateBookPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        idBookUpdatetf = new javax.swing.JTextField();
        categoryBookUpdatetf1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        authorBookUpdatetf1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        updateBookBtn = new javax.swing.JButton();
        titleBookUpdatetf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        updateCustomerPanel = new javax.swing.JPanel();
        fnCustomerUpdateTf1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lnCustomerUpdatetf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pnCiustomerUpdatetf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        updateCustomerBtn1 = new javax.swing.JButton();
        idCustomerUpdateTf = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        updateAuthorPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        fnAuthorUpdatetf = new javax.swing.JTextField();
        lnAuthorUpdatetf = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        eAuthorUpdatetf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        authorUpdateBtn = new javax.swing.JButton();
        idAuthorUpdatetf = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        deleteBookPanel = new javax.swing.JPanel();
        deleteBooktf = new javax.swing.JTextField();
        deleteBookBtn = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        deleteCustomerPanel = new javax.swing.JPanel();
        deleteCustomertf = new javax.swing.JTextField();
        deleteCustomerBtn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        deleteAuthorPanel = new javax.swing.JPanel();
        deleteAuthortf = new javax.swing.JTextField();
        deleteAuthorBtn = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        readBtn.setText("Read");
        readBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Welcome to the Bookshop");

        menuCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOOK", "CUSTOMER", "AUTHOR" }));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(readBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(menuCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(readBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(menuCB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        rightPanel.setLayout(new java.awt.CardLayout());

        createBookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Book"));

        jLabel2.setText("Category");

        jLabel3.setText("Title");

        jLabel4.setText("Author");

        addBookCreateBtn.setText("Add");

        javax.swing.GroupLayout createBookPanelLayout = new javax.swing.GroupLayout(createBookPanel);
        createBookPanel.setLayout(createBookPanelLayout);
        createBookPanelLayout.setHorizontalGroup(
            createBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createBookPanelLayout.createSequentialGroup()
                .addGroup(createBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createBookPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(createBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorBookCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryBookCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createBookPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(addBookCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(createBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createBookPanelLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(titleBookCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(295, Short.MAX_VALUE)))
            .addGroup(createBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createBookPanelLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
        );
        createBookPanelLayout.setVerticalGroup(
            createBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createBookPanelLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(categoryBookCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorBookCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(addBookCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(createBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createBookPanelLayout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(titleBookCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(432, Short.MAX_VALUE)))
            .addGroup(createBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createBookPanelLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(479, Short.MAX_VALUE)))
        );

        rightPanel.add(createBookPanel, "card2");

        createCustomerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Customer"));

        jLabel5.setText("First Name");

        jLabel6.setText("Last Name");

        jLabel7.setText("Phone number");

        addCustomerBtn.setText("Add");

        javax.swing.GroupLayout createCustomerPanelLayout = new javax.swing.GroupLayout(createCustomerPanel);
        createCustomerPanel.setLayout(createCustomerPanelLayout);
        createCustomerPanelLayout.setHorizontalGroup(
            createCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(createCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(fnCustomerCreateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnCustomerCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCiustomerCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(createCustomerPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(addCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        createCustomerPanelLayout.setVerticalGroup(
            createCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fnCustomerCreateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lnCustomerCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCiustomerCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(addCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.add(createCustomerPanel, "card3");

        createAuthorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Author"));

        jLabel8.setText("First Name");

        jLabel9.setText("Last Name");

        jLabel10.setText("email");

        authorCreateBtn.setText("Add");

        javax.swing.GroupLayout createAuthorPanelLayout = new javax.swing.GroupLayout(createAuthorPanel);
        createAuthorPanel.setLayout(createAuthorPanelLayout);
        createAuthorPanelLayout.setHorizontalGroup(
            createAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAuthorPanelLayout.createSequentialGroup()
                .addGroup(createAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAuthorPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(createAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(fnAuthorCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnAuthorCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eAuthorCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createAuthorPanelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(authorCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        createAuthorPanelLayout.setVerticalGroup(
            createAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAuthorPanelLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fnAuthorCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lnAuthorCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eAuthorCreatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(authorCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        rightPanel.add(createAuthorPanel, "card4");

        readBookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Read Book"));

        jLabel11.setText("Enter the id of the book");

        readBookBtn.setText("read");
        readBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBookBtnActionPerformed(evt);
            }
        });

        readAllBookBtn.setText("read all");
        readAllBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAllBookBtnActionPerformed(evt);
            }
        });

        readBookta.setColumns(20);
        readBookta.setRows(5);
        jScrollPane1.setViewportView(readBookta);

        javax.swing.GroupLayout readBookPanelLayout = new javax.swing.GroupLayout(readBookPanel);
        readBookPanel.setLayout(readBookPanelLayout);
        readBookPanelLayout.setHorizontalGroup(
            readBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readBookPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(readBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(readBookPanelLayout.createSequentialGroup()
                        .addComponent(readBookIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(readBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(readAllBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                    .addGroup(readBookPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        readBookPanelLayout.setVerticalGroup(
            readBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readBookPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(readBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(readAllBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(readBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readBookIdtf))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        rightPanel.add(readBookPanel, "card5");

        readCustomerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Read Customer"));

        jLabel12.setText("Enter the id of the customer");

        readCustomerBtn.setText("read");
        readCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readCustomerBtnActionPerformed(evt);
            }
        });

        readAllCustomerBtn.setText("read all");
        readAllCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAllCustomerBtnActionPerformed(evt);
            }
        });

        readCustomerta.setColumns(20);
        readCustomerta.setRows(5);
        jScrollPane2.setViewportView(readCustomerta);

        javax.swing.GroupLayout readCustomerPanelLayout = new javax.swing.GroupLayout(readCustomerPanel);
        readCustomerPanel.setLayout(readCustomerPanelLayout);
        readCustomerPanelLayout.setHorizontalGroup(
            readCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readCustomerPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(readCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(readCustomerPanelLayout.createSequentialGroup()
                        .addComponent(readCustomerIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(readCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(readAllCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                    .addGroup(readCustomerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        readCustomerPanelLayout.setVerticalGroup(
            readCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readCustomerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(readCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(readAllCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(readCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readCustomerIdtf))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        rightPanel.add(readCustomerPanel, "card5");

        readAuthorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Read Author"));

        jLabel13.setText("Enter the id of the author");

        readAuthorBtn.setText("read");

        readAllAuthorBtn.setText("read all");
        readAllAuthorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAllAuthorBtnActionPerformed(evt);
            }
        });

        readAuthorta.setColumns(20);
        readAuthorta.setRows(5);
        jScrollPane3.setViewportView(readAuthorta);

        javax.swing.GroupLayout readAuthorPanelLayout = new javax.swing.GroupLayout(readAuthorPanel);
        readAuthorPanel.setLayout(readAuthorPanelLayout);
        readAuthorPanelLayout.setHorizontalGroup(
            readAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readAuthorPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(readAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(readAuthorPanelLayout.createSequentialGroup()
                        .addComponent(readAuthorIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(readAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(readAllAuthorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                    .addGroup(readAuthorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        readAuthorPanelLayout.setVerticalGroup(
            readAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readAuthorPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(readAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(readAllAuthorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(readAuthorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readAuthorIdtf))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        rightPanel.add(readAuthorPanel, "card5");

        UpdateBookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Book"));

        jLabel14.setText("Category");

        jLabel15.setText("Title");

        jLabel16.setText("Author");

        updateBookBtn.setText("Update");

        jLabel17.setText("ID");

        javax.swing.GroupLayout UpdateBookPanelLayout = new javax.swing.GroupLayout(UpdateBookPanel);
        UpdateBookPanel.setLayout(UpdateBookPanelLayout);
        UpdateBookPanelLayout.setHorizontalGroup(
            UpdateBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateBookPanelLayout.createSequentialGroup()
                .addGroup(UpdateBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateBookPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(UpdateBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorBookUpdatetf1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryBookUpdatetf1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleBookUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idBookUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(UpdateBookPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(updateBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        UpdateBookPanelLayout.setVerticalGroup(
            UpdateBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateBookPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBookUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleBookUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(categoryBookUpdatetf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorBookUpdatetf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(updateBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        rightPanel.add(UpdateBookPanel, "card2");

        updateCustomerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Customer"));

        jLabel18.setText("First Name");

        jLabel19.setText("Last Name");

        jLabel20.setText("Phone number");

        updateCustomerBtn1.setText("Update");

        jLabel21.setText("ID");

        javax.swing.GroupLayout updateCustomerPanelLayout = new javax.swing.GroupLayout(updateCustomerPanel);
        updateCustomerPanel.setLayout(updateCustomerPanelLayout);
        updateCustomerPanelLayout.setHorizontalGroup(
            updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(updateCustomerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(idCustomerUpdateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(fnCustomerUpdateTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnCustomerUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCiustomerUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        updateCustomerPanelLayout.setVerticalGroup(
            updateCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCustomerPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCustomerUpdateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fnCustomerUpdateTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lnCustomerUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCiustomerUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(updateCustomerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        rightPanel.add(updateCustomerPanel, "card3");

        updateAuthorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Author"));

        jLabel22.setText("First Name");

        jLabel23.setText("Last Name");

        jLabel24.setText("email");

        authorUpdateBtn.setText("Add");

        jLabel25.setText("ID");

        javax.swing.GroupLayout updateAuthorPanelLayout = new javax.swing.GroupLayout(updateAuthorPanel);
        updateAuthorPanel.setLayout(updateAuthorPanelLayout);
        updateAuthorPanelLayout.setHorizontalGroup(
            updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(fnAuthorUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnAuthorUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eAuthorUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idAuthorUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)))
                    .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(authorUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        updateAuthorPanelLayout.setVerticalGroup(
            updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idAuthorUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fnAuthorUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lnAuthorUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eAuthorUpdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(authorUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        rightPanel.add(updateAuthorPanel, "card4");

        deleteBookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Book"));

        deleteBookBtn.setText("delete");

        jLabel26.setText("Enter the ID of the book");

        javax.swing.GroupLayout deleteBookPanelLayout = new javax.swing.GroupLayout(deleteBookPanel);
        deleteBookPanel.setLayout(deleteBookPanelLayout);
        deleteBookPanelLayout.setHorizontalGroup(
            deleteBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteBookPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(deleteBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(deleteBookPanelLayout.createSequentialGroup()
                        .addComponent(deleteBooktf, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteBookPanelLayout.setVerticalGroup(
            deleteBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteBookPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deleteBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBooktf)
                    .addComponent(deleteBookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(451, Short.MAX_VALUE))
        );

        rightPanel.add(deleteBookPanel, "card11");

        deleteCustomerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Customer"));

        deleteCustomertf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomertfActionPerformed(evt);
            }
        });

        deleteCustomerBtn.setText("delete");
        deleteCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerBtnActionPerformed(evt);
            }
        });

        jLabel27.setText("Enter the ID of the customer");

        javax.swing.GroupLayout deleteCustomerPanelLayout = new javax.swing.GroupLayout(deleteCustomerPanel);
        deleteCustomerPanel.setLayout(deleteCustomerPanelLayout);
        deleteCustomerPanelLayout.setHorizontalGroup(
            deleteCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCustomerPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(deleteCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(deleteCustomerPanelLayout.createSequentialGroup()
                        .addComponent(deleteCustomertf, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteCustomerPanelLayout.setVerticalGroup(
            deleteCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCustomerPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deleteCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteCustomertf)
                    .addComponent(deleteCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(451, Short.MAX_VALUE))
        );

        rightPanel.add(deleteCustomerPanel, "card11");

        deleteAuthorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Author"));

        deleteAuthorBtn.setText("delete");

        jLabel28.setText("Enter the ID of the Author");

        javax.swing.GroupLayout deleteAuthorPanelLayout = new javax.swing.GroupLayout(deleteAuthorPanel);
        deleteAuthorPanel.setLayout(deleteAuthorPanelLayout);
        deleteAuthorPanelLayout.setHorizontalGroup(
            deleteAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAuthorPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(deleteAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(deleteAuthorPanelLayout.createSequentialGroup()
                        .addComponent(deleteAuthortf, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteAuthorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteAuthorPanelLayout.setVerticalGroup(
            deleteAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAuthorPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deleteAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteAuthortf)
                    .addComponent(deleteAuthorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(451, Short.MAX_VALUE))
        );

        rightPanel.add(deleteAuthorPanel, "card11");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void readCustomerById() throws JSONException{
         String url ="http://localhost:8000/customer/read/"+ readCustomerIdtf.getText();
         if(readCustomerIdtf.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Please enter a customer id");
         }else{
         try {

		HttpClient httpClient = HttpClients.createDefault();
		HttpGet getRequest = new HttpGet(url);
		getRequest.addHeader("accept", "application/json");

		HttpResponse response = httpClient.execute(getRequest);

		if (response.getStatusLine().getStatusCode() != 200) {
			//throw new RuntimeException("Failed : HTTP error code : "
			 //  + response.getStatusLine().getStatusCode());
                         JOptionPane.showMessageDialog(null, "Error found check your connection-Http error code: "+ response.getStatusLine().getStatusCode());
		}

		BufferedReader br = new BufferedReader(
                         new InputStreamReader((response.getEntity().getContent())));

		String output;
		System.out.println("Output from Server .... \n");
                
                JSONObject obj;
              
		while ((output = br.readLine()) != null) {
                    
			System.out.println(output);
                        obj= new JSONObject(output); 
                        readCustomerta.append("id: "+obj.getString("id"));
                        readCustomerta.append("\n");
                        readCustomerta.append("first name: "+obj.getString("firstName"));
                        readCustomerta.append("\n");
                        readCustomerta.append("last name: "+obj.getString("lastName"));
                        readCustomerta.append("\n");
                        readCustomerta.append("phone number: "+obj.getString("phoneNumber")+"\n\n");
                    }
                
                


	  } catch (IOException | UnsupportedOperationException e) {
	
		e.printStackTrace();

	  } 
         }
    }
    
    public void readCustomerAll() throws JSONException{
         String url ="http://localhost:8000/customer/read/all";
         
         try {

		HttpClient httpClient = HttpClients.createDefault();
		HttpGet getRequest = new HttpGet(url);
		getRequest.addHeader("accept", "application/json");

		HttpResponse response = httpClient.execute(getRequest);

		if (response.getStatusLine().getStatusCode() != 200) {
			//throw new RuntimeException("Failed : HTTP error code : "
			 //  + response.getStatusLine().getStatusCode());
                         JOptionPane.showMessageDialog(null, "Error found check your connection-Http error code: "+ response.getStatusLine().getStatusCode());
		}

		BufferedReader br = new BufferedReader(
                         new InputStreamReader((response.getEntity().getContent())));

		String output;
		System.out.println("Output from Server .... \n");
                
              
              
		while ((output = br.readLine()) != null) {
                    
			System.out.println(output);
                      
                        readCustomerta.append(output);
                        readCustomerta.append("\n");
                        
                    }
                
                


	  } catch (IOException | UnsupportedOperationException e) {
	
		e.printStackTrace();

	  } 
         
    }
    
    public void deleteCustomerById(){
        
        String url ="http://localhost:8000/customer/delete/"+ deleteCustomertf.getText();
         if(deleteCustomertf.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Please enter a customer id");
         }else{
         try {

		HttpClient httpClient = HttpClients.createDefault();
		HttpGet deleteRequest = new HttpGet(url);

		HttpResponse response = httpClient.execute(deleteRequest);

		if (response.getStatusLine().getStatusCode() != 200) {
			//throw new RuntimeException("Failed : HTTP error code : "
			 //  + response.getStatusLine().getStatusCode());
                         JOptionPane.showMessageDialog(null, "Error found check your connection-Http error code: "+ response.getStatusLine().getStatusCode());
		}

                System.out.println("customer deleted");
                JOptionPane.showMessageDialog(null, "Customer deleted ");
		response.getEntity().getContent().close();;
                
         


	  } catch (IOException | UnsupportedOperationException e) {
	
		e.printStackTrace();

	  } 
         }
          
    }
    
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        switch (menuCB.getSelectedIndex()) {
            case 0:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(true);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            case 1:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(true);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            case 2:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(true);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_createBtnActionPerformed

    private void readAllBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAllBookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readAllBookBtnActionPerformed

    private void readAllCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAllCustomerBtnActionPerformed
        try {
            readCustomerAll();
        } catch (JSONException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readAllCustomerBtnActionPerformed

    private void readAllAuthorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAllAuthorBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readAllAuthorBtnActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed
        switch (menuCB.getSelectedIndex()) {
            case 0:
                readBookPanel.setVisible(true);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            case 1:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(true);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            case 2:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(true);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_readBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        switch (menuCB.getSelectedIndex()) {
            case 0:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(true);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            case 1:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(true);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            case 2:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(true);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        switch (menuCB.getSelectedIndex()) {
            case 0:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(true);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(false);
                break;
            case 1:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(true);
                deleteAuthorPanel.setVisible(false);
                break;
            case 2:
                readBookPanel.setVisible(false);
                readCustomerPanel.setVisible(false);
                readAuthorPanel.setVisible(false);
                createBookPanel.setVisible(false);
                createAuthorPanel.setVisible(false);
                createCustomerPanel.setVisible(false);
                UpdateBookPanel.setVisible(false);
                updateCustomerPanel.setVisible(false);
                updateAuthorPanel.setVisible(false);
                deleteBookPanel.setVisible(false);
                deleteCustomerPanel.setVisible(false);
                deleteAuthorPanel.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void readBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBookBtnActionPerformed
           
     
    }//GEN-LAST:event_readBookBtnActionPerformed

    private void readCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readCustomerBtnActionPerformed
        try {
            readCustomerById();
        } catch (JSONException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readCustomerBtnActionPerformed

    private void deleteCustomertfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomertfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustomertfActionPerformed

    private void deleteCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerBtnActionPerformed
        deleteCustomerById();
    }//GEN-LAST:event_deleteCustomerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdateBookPanel;
    private javax.swing.JButton addBookCreateBtn;
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JTextField authorBookCreatetf;
    private javax.swing.JTextField authorBookUpdatetf1;
    private javax.swing.JButton authorCreateBtn;
    private javax.swing.JButton authorUpdateBtn;
    private javax.swing.JTextField categoryBookCreatetf;
    private javax.swing.JTextField categoryBookUpdatetf1;
    private javax.swing.JPanel createAuthorPanel;
    private javax.swing.JPanel createBookPanel;
    private javax.swing.JButton createBtn;
    private javax.swing.JPanel createCustomerPanel;
    private javax.swing.JButton deleteAuthorBtn;
    private javax.swing.JPanel deleteAuthorPanel;
    private javax.swing.JTextField deleteAuthortf;
    private javax.swing.JButton deleteBookBtn;
    private javax.swing.JPanel deleteBookPanel;
    private javax.swing.JTextField deleteBooktf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteCustomerBtn;
    private javax.swing.JPanel deleteCustomerPanel;
    private javax.swing.JTextField deleteCustomertf;
    private javax.swing.JTextField eAuthorCreatetf;
    private javax.swing.JTextField eAuthorUpdatetf;
    private javax.swing.JTextField fnAuthorCreatetf;
    private javax.swing.JTextField fnAuthorUpdatetf;
    private javax.swing.JTextField fnCustomerCreateTf;
    private javax.swing.JTextField fnCustomerUpdateTf1;
    private javax.swing.JTextField idAuthorUpdatetf;
    private javax.swing.JTextField idBookUpdatetf;
    private javax.swing.JTextField idCustomerUpdateTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField lnAuthorCreatetf;
    private javax.swing.JTextField lnAuthorUpdatetf;
    private javax.swing.JTextField lnCustomerCreatetf;
    private javax.swing.JTextField lnCustomerUpdatetf;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> menuCB;
    private javax.swing.JTextField pnCiustomerCreatetf;
    private javax.swing.JTextField pnCiustomerUpdatetf;
    private javax.swing.JButton readAllAuthorBtn;
    private javax.swing.JButton readAllBookBtn;
    private javax.swing.JButton readAllCustomerBtn;
    private javax.swing.JButton readAuthorBtn;
    private javax.swing.JTextField readAuthorIdtf;
    private javax.swing.JPanel readAuthorPanel;
    private javax.swing.JTextArea readAuthorta;
    private javax.swing.JButton readBookBtn;
    private javax.swing.JTextField readBookIdtf;
    private javax.swing.JPanel readBookPanel;
    private javax.swing.JTextArea readBookta;
    private javax.swing.JButton readBtn;
    private javax.swing.JButton readCustomerBtn;
    private javax.swing.JTextField readCustomerIdtf;
    private javax.swing.JPanel readCustomerPanel;
    private javax.swing.JTextArea readCustomerta;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField titleBookCreatetf;
    private javax.swing.JTextField titleBookUpdatetf;
    private javax.swing.JPanel updateAuthorPanel;
    private javax.swing.JButton updateBookBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateCustomerBtn1;
    private javax.swing.JPanel updateCustomerPanel;
    // End of variables declaration//GEN-END:variables
}
